############ Case 1 - Example #########################
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "calculations_source",
    build_file = "//:external_dependency_buildfiles/calc.bazel",
    commit = "6b04a1238dd0d261481b01de03a2d865efae9f7b",
    remote = "https://github.com/BuildOpz/external-case1.git",
)